version: '3'
services:
  container_front:
    image: frontend-image
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - container_back
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://container_back:5000" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - BACKEND_URL=http://localhost:5000

  container_back:
    image: backend-image
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_URI=mongodb://mongodb_db:27017/mydatabase
      - PORT=5000

  mongodb_db:
    networks:
      - mynetwork
    image: mongo:latest
    ports:
      - "27017:27017"

networks:
  mynetwork: