version: '3'
services:
  mongodb_db:
      image: mongo:latest
      ports:
        - "27017:27017"
  frontend:
    image: frontend-image:latest
    ports:
      - '3000:3000'
    environment:
      - BACKEND_URL=http://localhost:5000
  backend:
    image: backend-image:latest
    ports:
      - '5000:5000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
        - MONGO_URI=mongodb://mongodb_db:27017/mydatabase
        - PORT=5000

  

      