version: '3'
services:
  frontend:
    image: frontend-image:latest
    ports:
      - '3000:3000'
    environment:
      - BACKEND_URL=http://localhost:5000
  backend:
    image: backend-image:latest
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI = "mongodb+srv://likhith:123@cluster0.9xogppr.mongodb.net/blog"
      # - JWT=a1cd158e2b34d47af6d0b446f59a326849f0dd8eb7ac51244f4ab4c1cb99552b9f856a8fb488f20fdbf0d489fc93b4d94fb71148a1bd24e2386a6c71e4d8a3cd